INSERT INTO products(id,tenant_id,commodity,group_name,variant_name,origins_json,source_ref,consulted_at,identity_status) VALUES
('product-01','eag-internal','soy','Soja','Soja GMO','["SITE"]','docs/eag-compass-perfil.md §3 item 1','2026-09-22','confirmed'),
('product-02','eag-internal','soy','Soja','Soja não GMO','["SITE"]','docs/eag-compass-perfil.md §3 item 2','2026-09-22','confirmed'),
('product-03','eag-internal','corn','Milho','Milho GMO','["SITE"]','docs/eag-compass-perfil.md §3 item 3','2026-09-22','confirmed'),
('product-04','eag-internal','corn','Milho','Milho não GMO','["SITE"]','docs/eag-compass-perfil.md §3 item 4','2026-09-22','confirmed'),
('product-05','eag-internal','coffee','Café','Café; Arábica e Robusta/Conilon como famílias previstas','["SOLICITACAO"]','docs/eag-compass-perfil.md §3 item 5','2026-09-22','confirmed'),
('product-06','eag-internal','sugar','Açúcar','ICUMSA 45','["SITE"]','docs/eag-compass-perfil.md §3 item 6','2026-09-22','confirmed'),
('product-07','eag-internal','sugar','Açúcar','ICUMSA 150','["SITE"]','docs/eag-compass-perfil.md §3 item 7','2026-09-22','confirmed'),
('product-08','eag-internal','sugar','Açúcar','VHP','["SITE"]','docs/eag-compass-perfil.md §3 item 8','2026-09-22','confirmed'),
('product-09','eag-internal','ethanol','Etanol','Etanol hidratado','["SITE"]','docs/eag-compass-perfil.md §3 item 9','2026-09-22','confirmed'),
('product-10','eag-internal','ethanol','Etanol','Etanol anidro','["SITE"]','docs/eag-compass-perfil.md §3 item 10','2026-09-22','confirmed'),
('product-11','eag-internal','industrial_alcohol','Álcool industrial','Álcool etílico neutro','["SITE"]','docs/eag-compass-perfil.md §3 item 11','2026-09-22','confirmed'),
('product-12','eag-internal','industrial_alcohol','Álcool industrial','Álcool etílico extra neutro','["SITE"]','docs/eag-compass-perfil.md §3 item 12','2026-09-22','confirmed'),
('product-13','eag-internal','industrial_alcohol','Álcool industrial','Álcool etílico hidratado (industrial)','["SITE"]','docs/eag-compass-perfil.md §3 item 13','2026-09-22','confirmed'),
('product-14','eag-internal','wheat','Cereais','Trigo','["SITE"]','docs/eag-compass-perfil.md §3 item 14','2026-09-22','confirmed'),
('product-15','eag-internal','sorghum','Cereais','Sorgo','["SITE", "SOLICITACAO"]','docs/eag-compass-perfil.md §3 item 15','2026-09-22','confirmed'),
('product-16','eag-internal','soy_meal','Farelos','Farelo de soja','["SITE"]','docs/eag-compass-perfil.md §3 item 16','2026-09-22','confirmed'),
('product-17','eag-internal','canola_meal','Farelos','Farelo de canola','["SITE"]','docs/eag-compass-perfil.md §3 item 17','2026-09-22','confirmed'),
('product-18','eag-internal','cotton_meal','Farelos','Farelo de algodão','["SITE"]','docs/eag-compass-perfil.md §3 item 18','2026-09-22','confirmed'),
('product-19','eag-internal','soy_oil','Óleos','Óleo de soja (bruto e refinado)','["SITE"]','docs/eag-compass-perfil.md §3 item 19','2026-09-22','confirmed'),
('product-20','eag-internal','canola_oil','Óleos','Óleo de canola','["SITE"]','docs/eag-compass-perfil.md §3 item 20','2026-09-22','confirmed'),
('product-21','eag-internal','cotton_oil','Óleos','Óleo de algodão','["SITE"]','docs/eag-compass-perfil.md §3 item 21','2026-09-22','confirmed'),
('product-22','eag-internal','palm_oil','Óleos','Óleo de palma (bruto e refinado)','["SITE"]','docs/eag-compass-perfil.md §3 item 22','2026-09-22','confirmed'),
('product-23','eag-internal','soy_lecithin','Derivados de soja','Lecitina de soja','["SITE"]','docs/eag-compass-perfil.md §3 item 23','2026-09-22','confirmed'),
('product-24','eag-internal','ddgs','Coprodutos','DDGS','["PORTFOLIO"]','docs/eag-compass-perfil.md §3 item 24','2026-09-22','confirmed'),
('product-25','eag-internal','cgf','Coprodutos','CGF','["PORTFOLIO"]','docs/eag-compass-perfil.md §3 item 25','2026-09-22','confirmed'),
('product-26','eag-internal','cgm','Coprodutos','CGM','["PORTFOLIO"]','docs/eag-compass-perfil.md §3 item 26','2026-09-22','confirmed'),
('product-27','eag-internal','uco','Óleos residuais','UCO','["PORTFOLIO"]','docs/eag-compass-perfil.md §3 item 27','2026-09-22','confirmed'),
('product-28','eag-internal','cso','Óleos','CSO','["PORTFOLIO"]','docs/eag-compass-perfil.md §3 item 28','2026-09-22','pending');
INSERT INTO product_characteristics(id,product_id,char_key,char_value,source_ref,status,sample_only) VALUES ('sample-soy-oil','product-19','sample_scope','Laudo restrito à amostra analisada; não é especificação de oferta.','docs/eag-compass-perfil.md §3 item 19','confirmed',1);
