UPDATE parameters SET effective_to='2026-09-22T00:00:00Z' WHERE parameter_key='volume_min' AND scope_key IN ('sugar','coffee:FoodEra');
INSERT INTO parameters(id,tenant_id,parameter_key,scope_key,value_json,effective_from,changed_by,change_reason) VALUES ('v2-param-0','eag-internal','radius_allowed_km','national','[5, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500]','2026-09-22T00:00:00Z','system-admin','Spec v2.0 aprovada; valores B3 e rampa documentados');
INSERT INTO parameters(id,tenant_id,parameter_key,scope_key,value_json,effective_from,changed_by,change_reason) VALUES ('v2-param-1','eag-internal','radius_default_km','national','5','2026-09-22T00:00:00Z','system-admin','Spec v2.0 aprovada; valores B3 e rampa documentados');
INSERT INTO parameters(id,tenant_id,parameter_key,scope_key,value_json,effective_from,changed_by,change_reason) VALUES ('v2-param-2','eag-internal','send_daily_ramp','email','[5, 10, 15, 20]','2026-09-22T00:00:00Z','system-admin','Spec v2.0 aprovada; valores B3 e rampa documentados');
INSERT INTO parameters(id,tenant_id,parameter_key,scope_key,value_json,effective_from,changed_by,change_reason) VALUES ('v2-param-3','eag-internal','send_interval_minutes','email','{"min": 15, "max": 25}','2026-09-22T00:00:00Z','system-admin','Spec v2.0 aprovada; valores B3 e rampa documentados');
INSERT INTO parameters(id,tenant_id,parameter_key,scope_key,value_json,effective_from,changed_by,change_reason) VALUES ('v2-param-4','eag-internal','send_stop_hard_bounce_pct','email','3','2026-09-22T00:00:00Z','system-admin','Spec v2.0 aprovada; valores B3 e rampa documentados');
INSERT INTO parameters(id,tenant_id,parameter_key,scope_key,value_json,effective_from,changed_by,change_reason) VALUES ('v2-param-5','eag-internal','send_step_up_max_hard_bounce_pct','email','2','2026-09-22T00:00:00Z','system-admin','Spec v2.0 aprovada; valores B3 e rampa documentados');
INSERT INTO parameters(id,tenant_id,parameter_key,scope_key,value_json,effective_from,changed_by,change_reason) VALUES ('v2-param-6','eag-internal','volume_min','sugar:international','500','2026-09-22T00:00:00Z','system-admin','Spec v2.0 aprovada; valores B3 e rampa documentados');
INSERT INTO parameters(id,tenant_id,parameter_key,scope_key,value_json,effective_from,changed_by,change_reason) VALUES ('v2-param-7','eag-internal','volume_min','coffee:international:FoodEra','5','2026-09-22T00:00:00Z','system-admin','Spec v2.0 aprovada; valores B3 e rampa documentados');
