-- Correção de classificação (2026-10-01, pedido de Rogério): 5 notificações automáticas do LinkedIn lidas como "human"
-- no teste interno da ponte. Sem empresa, sequência, tarefa, pausa ou supressão ligadas; só a classificação muda.
-- Cada linha só muda se ainda estiver como lida (guarda); a auditoria registra o valor anterior e o novo.
INSERT INTO audit_log(id,tenant_id,actor_id,actor_role,action,entity_type,entity_id,field_name,old_value_json,new_value_json,reason,request_id) SELECT lower(hex(randomblob(16))),tenant_id,'system-correction','system','inbound.reclassified','inbound_message',id,'classification','"human"','"auto_reply"','Notificação automática do LinkedIn (Message-ID *.prod.linkedin.com, sem thread); correção pedida por Rogério em 2026-10-01; regra nova no classificador com teste de regressão','correcao-linkedin-2026-10-01' FROM inbound_messages WHERE id='334c7138-eb9a-487f-bdbc-955dd7906c11' AND classification='human' AND correlation='none' AND company_id IS NULL AND outbox_id IS NULL AND message_id LIKE '%.prod.linkedin.com>';
UPDATE inbound_messages SET classification='auto_reply' WHERE id='334c7138-eb9a-487f-bdbc-955dd7906c11' AND classification='human' AND correlation='none' AND company_id IS NULL AND outbox_id IS NULL AND message_id LIKE '%.prod.linkedin.com>';
INSERT INTO audit_log(id,tenant_id,actor_id,actor_role,action,entity_type,entity_id,field_name,old_value_json,new_value_json,reason,request_id) SELECT lower(hex(randomblob(16))),tenant_id,'system-correction','system','inbound.reclassified','inbound_message',id,'classification','"human"','"auto_reply"','Notificação automática do LinkedIn (Message-ID *.prod.linkedin.com, sem thread); correção pedida por Rogério em 2026-10-01; regra nova no classificador com teste de regressão','correcao-linkedin-2026-10-01' FROM inbound_messages WHERE id='d8e10e3d-d515-4860-b7e4-386ec13e0b5e' AND classification='human' AND correlation='none' AND company_id IS NULL AND outbox_id IS NULL AND message_id LIKE '%.prod.linkedin.com>';
UPDATE inbound_messages SET classification='auto_reply' WHERE id='d8e10e3d-d515-4860-b7e4-386ec13e0b5e' AND classification='human' AND correlation='none' AND company_id IS NULL AND outbox_id IS NULL AND message_id LIKE '%.prod.linkedin.com>';
INSERT INTO audit_log(id,tenant_id,actor_id,actor_role,action,entity_type,entity_id,field_name,old_value_json,new_value_json,reason,request_id) SELECT lower(hex(randomblob(16))),tenant_id,'system-correction','system','inbound.reclassified','inbound_message',id,'classification','"human"','"auto_reply"','Notificação automática do LinkedIn (Message-ID *.prod.linkedin.com, sem thread); correção pedida por Rogério em 2026-10-01; regra nova no classificador com teste de regressão','correcao-linkedin-2026-10-01' FROM inbound_messages WHERE id='2f65f86f-0c81-4c5c-a7c5-f72547456c63' AND classification='human' AND correlation='none' AND company_id IS NULL AND outbox_id IS NULL AND message_id LIKE '%.prod.linkedin.com>';
UPDATE inbound_messages SET classification='auto_reply' WHERE id='2f65f86f-0c81-4c5c-a7c5-f72547456c63' AND classification='human' AND correlation='none' AND company_id IS NULL AND outbox_id IS NULL AND message_id LIKE '%.prod.linkedin.com>';
INSERT INTO audit_log(id,tenant_id,actor_id,actor_role,action,entity_type,entity_id,field_name,old_value_json,new_value_json,reason,request_id) SELECT lower(hex(randomblob(16))),tenant_id,'system-correction','system','inbound.reclassified','inbound_message',id,'classification','"human"','"auto_reply"','Notificação automática do LinkedIn (Message-ID *.prod.linkedin.com, sem thread); correção pedida por Rogério em 2026-10-01; regra nova no classificador com teste de regressão','correcao-linkedin-2026-10-01' FROM inbound_messages WHERE id='aeccb56f-8d28-4dcf-b48b-0ab1e26df4c8' AND classification='human' AND correlation='none' AND company_id IS NULL AND outbox_id IS NULL AND message_id LIKE '%.prod.linkedin.com>';
UPDATE inbound_messages SET classification='auto_reply' WHERE id='aeccb56f-8d28-4dcf-b48b-0ab1e26df4c8' AND classification='human' AND correlation='none' AND company_id IS NULL AND outbox_id IS NULL AND message_id LIKE '%.prod.linkedin.com>';
INSERT INTO audit_log(id,tenant_id,actor_id,actor_role,action,entity_type,entity_id,field_name,old_value_json,new_value_json,reason,request_id) SELECT lower(hex(randomblob(16))),tenant_id,'system-correction','system','inbound.reclassified','inbound_message',id,'classification','"human"','"auto_reply"','Notificação automática do LinkedIn (Message-ID *.prod.linkedin.com, sem thread); correção pedida por Rogério em 2026-10-01; regra nova no classificador com teste de regressão','correcao-linkedin-2026-10-01' FROM inbound_messages WHERE id='585b88f2-4c5b-46d3-84d2-701f0a203995' AND classification='human' AND correlation='none' AND company_id IS NULL AND outbox_id IS NULL AND message_id LIKE '%.prod.linkedin.com>';
UPDATE inbound_messages SET classification='auto_reply' WHERE id='585b88f2-4c5b-46d3-84d2-701f0a203995' AND classification='human' AND correlation='none' AND company_id IS NULL AND outbox_id IS NULL AND message_id LIKE '%.prod.linkedin.com>';
